import { api } from '@/lib/api';
import {AIQueryRequest, AIQueryResponse, ReportResponse, ReportDetailResponse } from '@/types/reports';

export const reportService = {
  /**
   * Generate a new report for a specific month
   * POST /reports/generate?report_month=YYYY-MM-DD
   */
  generateReport: async (reportMonth: string): Promise<ReportResponse> => {
    const response = await api.post<ReportResponse>('/reports/generate', {
       report_month: reportMonth,
    });
    return response.data;
  },

  /**
   * Get all reports generated by the logged-in user
   * GET /reports
   */
  getMyReports: async (): Promise<ReportResponse[]> => {
    const response = await api.get<ReportResponse[]>('/reports');
    return response.data;
  },

  /**
   * Get detailed report by ID (includes classwise data breakup)
   * GET /reports/{report_id}
   */
  getReport: async (reportId: number): Promise<ReportDetailResponse> => {
    const response = await api.get<ReportDetailResponse>(`/reports/${reportId}`);
    return response.data;
  },

  /**
   * Refresh a report calculation with updated school/enrollment data
   * PUT /reports/{report_id}/refresh
   */
  refreshReport: async (reportId: number): Promise<ReportDetailResponse> => {
    const response = await api.put<ReportDetailResponse>(`/reports/${reportId}/refresh`);
    return response.data;
  },

  /**
   * Lock/finalize a report status
   * POST /reports/{report_id}/finalize
   */
  finalizeReport: async (reportId: number): Promise<ReportResponse> => {
    const response = await api.post<ReportResponse>(`/reports/${reportId}/finalize`);
    return response.data;
  },

  askAiQuery: async (payload: AIQueryRequest): Promise<AIQueryResponse> => {
    const response = await api.post<AIQueryResponse>('/reports/ai-query', {
      question: payload.question.trim(),
      target_date: payload.target_date, 
    });
    return response.data;
  },
};