"""create table model

Revision ID: 576d54c11197
Revises: 
Create Date: 2026-08-03 19:22:37.088719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576d54c11197'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('SC', 'OBC', 'GENERAL', 'BC', name='categoryenum'), nullable=False),
    sa.Column('boys', sa.Integer(), nullable=False,server_default='0'),
    sa.Column('girls', sa.Integer(), nullable=False,server_default='0'),
    sa.Column('below_6', sa.Integer(), nullable=False,server_default='0'),
    sa.Column('between_6_and_11', sa.Integer(), nullable=False,server_default='0'),
    sa.Column('above_11', sa.Integer(), nullable=False,server_default='0'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_', 'category', name='uq_school_class_category')
    )
    op.create_index(op.f('ix_enrollment_data_id'), 'enrollment_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_data_id'), table_name='enrollment_data')
    op.drop_table('enrollment_data')
    op.drop_table('schools')
    op.drop_table('users')
    # ### end Alembic commands ###
