"""create reports tables

Revision ID: 889a5ded4012
Revises: 576d54c11197
Create Date: 2026-08-12 11:33:13.967752

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM
from alembic import op
import sqlalchemy as sa

category_enum = ENUM('SC', 'OBC', 'GENERAL', 'BC', name='categoryenum', create_type=False)


# revision identifiers, used by Alembic.
revision: str = '889a5ded4012'
down_revision: Union[str, Sequence[str], None] = '576d54c11197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_month', name='uq_user_report_month')
    )
    op.create_table('report_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_', sa.Integer(), nullable=False),
    sa.Column('category', category_enum, nullable=False),
    sa.Column('boys', sa.Integer(), nullable=False),
    sa.Column('girls', sa.Integer(), nullable=False),
    sa.Column('below_6', sa.Integer(), nullable=False),
    sa.Column('between_6_and_11', sa.Integer(), nullable=False),
    sa.Column('above_11', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_data')
    op.drop_table('reports')
    # ### end Alembic commands ###
