"""create reports table for status

Revision ID: ef17512fe729
Revises: 889a5ded4012
Create Date: 2026-08-12 17:01:40.710432

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef17512fe729'
down_revision: Union[str, Sequence[str], None] = '889a5ded4012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

report_status_enum = postgresql.ENUM('DRAFT', 'END', name='reportstatus')
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    report_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('reports', sa.Column('status', report_status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'status')
    report_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
