"""add school operator table

Revision ID: ef88070398a8
Revises: ef17512fe729
Create Date: 2026-10-03 18:18:46.175139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef88070398a8'
down_revision: Union[str, Sequence[str], None] = 'ef17512fe729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'user_id', name='uq_operator_school')
    )
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'END', name='reportstatus'),
               nullable=False)
    
    op.add_column('schools', sa.Column('operator_passcode', sa.String(), nullable=True))
    
    op.execute("""
        UPDATE schools 
        SET operator_passcode = 'SCH-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT || id::TEXT) FROM 1 FOR 6))
        WHERE operator_passcode IS NULL;
    """)
    op.create_unique_constraint(None, 'schools', ['operator_passcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'operator_passcode')
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'END', name='reportstatus'),
               nullable=True)
    op.drop_table('school_operators')
    # ### end Alembic commands ###
